### ISSUE TITLE
Draft a reference tree

### ISSUE THREAD

**Issue by j23414** [j23414/nextclade_dengue#1]
1. Pull all sequences
2. Build a tree
3. Subsample tree to get representatives within each clade, maybe using augur filter, maybe using [smot](https://github.com/flu-crew/smot)

**Comment by j23414** [comment]
4. Pick a reasonable outgroup
5. Pick whole genome vs gene alignment, the overhang will result in worse P scores

* https://docs.nextstrain.org/projects/nextclade/en/stable/user/algorithm/07-quality-control.html#private-mutations-p

**Comment by j23414** [comment]
Tried the live build trees, dig into:

```
Error message: Error: When initializing Nextclade runner: When preprocessing reference tree node NODE_0000097: amino acid mutation M:D89E is outside of the peptide M (length 75). This is likely an inconsistency between reference tree, reference sequence, and gene map in the Nextclade dataset
Nextclade version 2.14.1 (commit: 85e00e8, branch: release)
Memory available: 3586 MBytes
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Browser details: {"browser":{"name":"Chrome","version":"113.0.0.0"},"os":{"name":"macOS","version":"10.15.7","versionName":"Catalina"},"platform":{"type":"desktop","vendor":"Apple"},"engine":{"name":"Blink"}}
Call stack:
Error: When initializing Nextclade runner: When preprocessing reference tree node NODE_0000097: amino acid mutation M:D89E is outside of the peptide M (length 75). This is likely an inconsistency between reference tree, reference sequence, and gene map in the Nextclade dataset
    at M (https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:15774)
    at https://clades.nextstrain.org/_next/static/wasm/cf835b4f9fbcf56c.wasm:wasm-function[1547]:0x1e3d5c
    at new a (https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:9424)
    at https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:24056
    at u (https://clades.nextstrain.org/_next/static/chunks/444.170c49d0571b2ba1.js:1:28086)
    at Generator._invoke (https://clades.nextstrain.org/_next/static/chunks/444.170c49d0571b2ba1.js:1:29376)
    at a.<computed> [as next] (https://clades.nextstrain.org/_next/static/chunks/444.170c49d0571b2ba1.js:1:28489)
    at p (https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:21841)
    at d (https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:22038)
    at https://clades.nextstrain.org/_next/static/chunks/68.daad1778960b5734.js:1:22097
```

**Comment by j23414** [comment]
Test <sup>superscript</sup> and <sub>subscript</sub> in order to reference more information <sup>1</sup>

<sup>1</sup> [https://gist.github.com/bt5e/7507535](https://gist.github.com/bt5e/7507535)

**Comment by j23414** [comment]
Double check

* https://github.com/j23414/nextclade_dengue/blob/main/all/genemap.gff#L5

Against

* https://github.com/nextstrain/dengue/blob/main/config/clades_genotypes.tsv
